// This file is auto-generated by scripts/generate-models.ts
// Do not edit manually - run 'npm run generate-models' to update

import values from "./data/zai-api.json" with { type: "json" };
import { flattenModelCatalog, type ModelCatalog } from "../model-catalog.ts";

export const ZAI_API_MODELS: ModelCatalog<typeof values, "zai-api"> =
	flattenModelCatalog("zai-api", values);
